# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

# [[main]]
#   name = "About us"
#   pageRef = "index.html"
#   weight = 10

[[main]]
 name = "News"
 pageRef = "posts"
 weight = 10

[[main]]
 name = "People"
 pageRef = "people/ppl"
 weight = 30

[[main]]
 name = "Our work"
 weight = 40

[[main]]
 name = "Projects"
 parent = "Our work"
 pageRef = "projects"
 weight = 20

[[main]]
  name = "Publications"
  pageRef = "publications"
  parent = "Our work"
  weight = 40

[[main]]
  name = "NeuroGDA"
  url = "https://neurogda.gumed.edu.pl/"
  parent = "Our work"
  weight = 40

[[main]]
  name = 'Participate'
  parent = "Our work"
  url = "https://airtable.com/apptqpO1FEw7mXfBL/pagxNYspvZP0uCVFE/form"
  weight = 50

[[main]]
  name = '{{< icon "bluesky" >}}'
  url = "http://kbas.bsky.social"
  weight = 60

[[main]]
  name = '{{< icon "linkedin" >}}'
  url = 'https://www.linkedin.com/company/auditory-neuroscience-laboratory/'
  weight = 70

# -- Footer Menu --
# # The footer menu is displayed at the bottom of the page, just before
# # the copyright notice. Configure as per the main menu above.


[[footer]]
  name = '{{< figure src="logo_ncn.png" default=true width="400" >}}'
  url = "http://ncn.gov.pl"
  weight = 10

[[footer]]
  name = '{{< figure src="gumed.png" default=true width="350" >}}'
  url = "http://gumed.edu.pl"
  weight = 20
